name: Simpleheal
version: '${project.version}'
main: com.guedosha.simpleheal.Simpleheal
api-version: 1.16
authors: [ Guedosha ]
description: A simple yet highly configurable Spigot plugin to heal you
website: https://www.guedosha.com
commands:
  heal:
    description: Heals you to full health
    usage: /<command>, /<command> <target>
  reload:
    description: Reloads the config
    usage: /simpleheal:reload