name: Simpleheal
version: '${project.version}'
main: com.guedosha.simpleheal.Simpleheal
api-version: 1.19
authors: [ Guedosha ]
description: Adds a simple /heal command
website: https://www.guedosha.com
commands:
  heal:
    description: Heals you to full health
    usage: /<command>